package com.nncollege.module;
public enum ModuleType {
 COLLEGE, STUDENT, ACADEMIC, FACULTY, ATTENDANCE, EXAMINATION, FACULTY_TASK, LIBRARY, FEE, DOCUMENT, PROJECT, INTERNSHIP, PLACEMENT, HOSTEL, TRANSPORT, TIMETABLE, NOTIFICATION, PARENT, REPORTING
}