server:
  port: 8080
spring:
  application:
    name: nnit-college360
  datasource:
    url: jdbc:mysql://localhost:3306/college360?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
college360:
  integrations:
    notification-base-url: ${NOTIFICATION_BASE_URL:http://localhost:8081}
